// Generated by https://quicktype.io

export interface BridgeResponse {
  "@odata.context":  string;
  "@odata.nextLink": string;
  "@odata.count":    number;
  value:             Value[];
}

export interface Value {
  "@odata.context":                    string;
  "@odata.id":                         string;
  StreetDirPrefix:                     StreetDirPrefix | null;
  PublicSurveyRange:                   null | string;
  LandLeaseAmountFrequency:            Frequency | null;
  BedroomsTotal:                       number | null;
  ShowingInstructions:                 string;
  LeaseAssignableYN:                   boolean | null;
  LivingAreaUnits:                     Units;
  CoListAgentDirectPhone:              null | string;
  SeatingCapacity:                     null;
  CoolingYN:                           boolean | null;
  ListAgentKey:                        string;
  InsuranceExpense:                    null;
  TaxLegalDescription:                 null | string;
  CarportSpaces:                       number | null;
  YearEstablished:                     null;
  OnMarketDate:                        string;
  LotSizeUnits:                        Units;
  ListAgentEmail:                      string;
  ContractStatusChangeDate:            string;
  ContingentDate:                      null;
  LaundryFeatures:                     LaundryFeature[];
  MajorChangeTimestamp:                string;
  LeaseAmountFrequency:                Frequency | null;
  Flooring:                            Flooring[];
  PhotosCount:                         number;
  CoBuyerAgentEmail:                   null | string;
  AdditionalParcelsYN:                 boolean | null;
  WaterfrontFeatures:                  string[];
  CoBuyerAgentDirectPhone:             null | string;
  RoomBedroomFeatures:                 RoomBedroomFeature[];
  SubAgencyCompensation:               null | string;
  ViewYN:                              boolean;
  SeniorCommunityYN:                   boolean;
  Cooling:                             Cooling[];
  GarageYN:                            boolean | null;
  ExteriorFeatures:                    string[];
  StatusChangeTimestamp:               string;
  AvailabilityDate:                    null | string;
  Longitude:                           number;
  SecurityFeatures:                    string[];
  BuyerAgentFullName:                  null | string;
  Skirt:                               any[];
  DocumentsCount:                      null;
  CarportYN:                           boolean | null;
  PublicRemarks:                       null | string;
  MIAMIRE_TypeofAssociation:           MIAMIRETypeofAssociation[];
  CancelationDate:                     null;
  FinancialDataSource:                 any[];
  TaxExemptions:                       string[];
  BuildingName:                        null | string;
  CoBuyerAgentKey:                     null | string;
  AssociationFeeFrequency:             Frequency | null;
  CurrentFinancing:                    CurrentFinancing[];
  NumberOfFullTimeEmployees:           null;
  HeatingYN:                           boolean | null;
  CoBuyerAgentStateLicense:            null | string;
  OffMarketTimestamp:                  null | string;
  ManagerExpense:                      null;
  CoListOfficeName:                    null | string;
  MIAMIRE_AdjustedAreaSF:              number | null;
  RoadSurfaceType:                     string[];
  PriceChangeTimestamp:                null | string;
  RoomDiningRoomFeatures:              RoomDiningRoomFeature[];
  ListingKeyNumeric:                   number;
  MajorChangeType:                     MajorChangeType;
  ListingContractDate:                 string;
  CoListOfficeKey:                     null | string;
  Zoning:                              null | string;
  Appliances:                          Appliance[];
  MaintenanceExpense:                  number | null;
  ListAOR:                             ListAOR;
  MLSAreaMajor:                        null | string;
  TaxAnnualAmount:                     number | null;
  ListOfficeName:                      string;
  CoBuyerOfficeName:                   null | string;
  MIAMIRE_SellerContributionsYN:       boolean | null;
  MIAMIRE_RATIO_CurrentPrice_By_SQFT:  number | null;
  MIAMIRE_MaximumLeasableSqft:         number | null;
  LandLeaseAmount:                     number | null;
  CurrentUse:                          string[];
  OriginatingSystemKey:                OriginatingSystem;
  BusinessType:                        string[];
  CountyOrParish:                      CountyOrParish;
  DualVariableCompensationYN:          boolean;
  Latitude:                            number;
  PropertyType:                        PropertyType;
  BathroomsTotalDecimal:               number | null;
  PhotosChangeTimestamp:               null | string;
  ListPrice:                           number;
  RoadFrontageType:                    string[];
  OriginatingSystemName:               OriginatingSystemName;
  ListOfficePhone:                     null | string;
  AssociationYN:                       boolean;
  DOH1:                                null;
  MlsStatus:                           MajorChangeType;
  StreetNumber:                        string;
  GrossScheduledIncome:                null;
  CoBuyerOfficeKey:                    null | string;
  CoListOfficeMlsId:                   null | string;
  LeaseTerm:                           LeaseTerm | null;
  ListingKey:                          string;
  MIAMIRE_SellerContributionsAmt:      number | null;
  StateOrProvince:                     StateOrProvince;
  CommonWalls:                         any[];
  DistanceToSewerComments:             null;
  CoveredSpaces:                       number | null;
  MiddleOrJuniorSchool:                null | string;
  MIAMIRE_PoolYN:                      boolean | null;
  VirtualTourURLUnbranded:             null | string;
  ShowingContactType:                  ShowingContactType[];
  Vegetation:                          string[];
  Gas:                                 any[];
  CoListAgentEmail:                    null | string;
  ElementarySchool:                    null | string;
  FrontageLength:                      null | string;
  MIAMIRE_TypeofGoverningBodies:       MIAMIRETypeofGoverningBodies | null;
  StreetDirSuffix:                     null;
  CoBuyerOfficePhone:                  null | string;
  Disclosures:                         string[];
  ListOfficeKey:                       string;
  FireplaceYN:                         boolean | null;
  Directions:                          null | string;
  BridgeModificationTimestamp:         string;
  EntryLevel:                          number | null;
  ListAgentFullName:                   string;
  AttachedGarageYN:                    boolean | null;
  StandardStatus:                      MajorChangeType;
  Roof:                                string[];
  PropertyCondition:                   PropertyCondition[];
  ParkingTotal:                        number | null;
  ListAgentOfficePhone:                null | string;
  FrontageType:                        FrontageType[];
  Stories:                             number | null;
  DevelopmentStatus:                   string[];
  GrossIncome:                         null;
  ParcelNumber:                        null | string;
  PoolPrivateYN:                       boolean;
  ListingTerms:                        ListingTerm[];
  View:                                string[];
  OperatingExpense:                    null;
  SignOnPropertyYN:                    boolean;
  BuyerAgentStateLicense:              null | string;
  PropertySubType:                     PropertySubType | null;
  LeaseRenewalOptionYN:                boolean | null;
  YearBuiltDetails:                    YearBuiltDetails | null;
  BuyerAgentDirectPhone:               null | string;
  OtherExpense:                        number;
  Possession:                          Possession[];
  HighSchool:                          null | string;
  CoListAgentOfficePhone:              null | string;
  LeaseConsideredYN:                   boolean | null;
  HomeWarrantyYN:                      null;
  Levels:                              string[];
  OperatingExpenseIncludes:            any[];
  IDXParticipationYN:                  boolean;
  DistanceToFreewayNumeric:            null;
  InteriorFeatures:                    string[];
  BathroomsFull:                       number | null;
  WaterfrontYN:                        boolean;
  LotSizeAcres:                        number | null;
  SubdivisionName:                     null | string;
  OffMarketDate:                       null | string;
  SpecialLicenses:                     any[];
  CoBuyerAgentMlsId:                   null | string;
  Fencing:                             Fencing[];
  InternetAddressDisplayYN:            boolean;
  WithdrawnDate:                       null;
  MIAMIRE_GuestHouseDescription:       string[];
  MIAMIRE_PetsAllowedYN:               boolean | null;
  Contingency:                         Contingency | null;
  ApprovalStatus:                      null | string;
  CloseDate:                           null | string;
  StreetSuffix:                        null;
  ListAgentMlsId:                      string;
  HorseAmenities:                      string[];
  ListingService:                      null | string;
  Elevation:                           null;
  WaterSource:                         WaterSource[];
  LotSizeDimensions:                   null | string;
  DoorFeatures:                        DoorFeature[];
  StoriesTotal:                        number | null;
  ModificationTimestamp:               string;
  YearBuilt:                           number | null;
  ElectricOnPropertyYN:                boolean | null;
  PropertyAttachedYN:                  boolean | null;
  BuyerAgentKey:                       null | string;
  TaxLot:                              null | string;
  BusinessName:                        null;
  BuyerAgentEmail:                     null | string;
  MIAMIRE_ForLeaseYN:                  boolean | null;
  Coordinates:                         number[];
  CoBuyerOfficeMlsId:                  null | string;
  OriginatingSystemID:                 OriginatingSystem;
  LandLeaseYN:                         boolean | null;
  PreviousListPrice:                   number | null;
  HorseYN:                             boolean;
  PetsAllowed:                         PetsAllowed[];
  DaysOnMarket:                        number;
  MIAMIRE_MaintenanceIncludes:         string[];
  UnitNumber:                          null | string;
  OpenParkingYN:                       boolean | null;
  TransactionBrokerCompensation:       null | string;
  BuyerAgencyCompensationType:         CompensationType | null;
  NetOperatingIncome:                  null;
  MIAMIRE_PoolDimensions:              null | string;
  OtherStructures:                     OtherStructure[];
  AssociationAmenities:                string[];
  ListOfficeMlsId:                     string;
  Inclusions:                          null | string;
  ClosePrice:                          number | null;
  VirtualTourURLZillow:                null;
  ListAgentDirectPhone:                null | string;
  CoBuyerAgentOfficePhone:             null | string;
  CoListAgentFullName:                 null | string;
  CoListAgentKey:                      null | string;
  PendingTimestamp:                    null | string;
  StreetNumberNumeric:                 number;
  EntryLocation:                       EntryLocation | null;
  MIAMIRE_ForSaleMLSNumber:            null | string;
  SpaYN:                               boolean | null;
  SpaFeatures:                         string[];
  LivingArea:                          number | null;
  ExistingLeaseType:                   any[];
  CoListAgentStateLicense:             null | string;
  ParkingFeatures:                     string[];
  PostalCodePlus4:                     null | string;
  BathroomsHalf:                       number | null;
  Supplements:                         Supplement[] | null;
  RoomLivingRoomFeatures:              string[];
  PoolFeatures:                        string[];
  NumberOfUnitsInCommunity:            number | null;
  Sewer:                               Sewer[];
  ExpirationDate:                      string;
  SyndicationRemarks:                  null | string;
  Heating:                             Heating[];
  MIAMIRE_LPAmtSqFt:                   number | null;
  StructureType:                       string[];
  BuildingAreaSource:                  null | string;
  Model:                               null | string;
  BuilderModel:                        null | string;
  TrashExpense:                        null;
  TotalActualRent:                     number | null;
  ListAgentStateLicense:               null | string;
  CoListAgentMlsId:                    null | string;
  PublicSurveyTownship:                null | string;
  StreetName:                          string;
  ListOfficeFax:                       null | string;
  PatioAndPorchFeatures:               PatioAndPorchFeature[];
  BuyerOfficePhone:                    null | string;
  ListingAgreement:                    ListingAgreement | null;
  RoadResponsibility:                  string[];
  PublicSurveySection:                 null | string;
  Utilities:                           string[];
  FireplaceFeatures:                   string[];
  ListingId:                           string;
  WindowFeatures:                      string[];
  SpecialListingConditions:            SpecialListingCondition[];
  NewConstructionYN:                   boolean;
  CommunityFeatures:                   string[];
  BathroomsTotalInteger:               number | null;
  RoomsTotal:                          number | null;
  NumberOfBuildings:                   null;
  GarageSpaces:                        number | null;
  OriginalListPrice:                   number;
  GreenEnergyEfficient:                string[];
  Media:                               Media[] | null;
  BuildingAreaUnits:                   Units;
  RentIncludes:                        string[];
  City:                                string;
  InternetEntireListingDisplayYN:      boolean;
  BuyerAgentOfficePhone:               null | string;
  BuyerAgencyCompensation:             null | string;
  InternetAutomatedValuationDisplayYN: boolean;
  AccessibilityFeatures:               string[];
  TaxYear:                             number | null;
  BuildingFeatures:                    string[];
  OriginalEntryTimestamp:              string;
  OwnershipType:                       null;
  SourceSystemKey:                     string;
  Ownership:                           null;
  BuyerAgentMlsId:                     null | string;
  DirectionFaces:                      DirectionFaces | null;
  LotFeatures:                         string[];
  PostalCode:                          string;
  PossibleUse:                         PossibleUse[];
  Furnished:                           Furnished | null;
  BuyerOfficeMlsId:                    null | string;
  DocumentsAvailable:                  string[];
  ConstructionMaterials:               ConstructionMaterial[];
  MIAMIRE_SubdivisionInformation:      string[];
  SuppliesExpense:                     null;
  ListOfficeURL:                       null | string;
  MIAMIRE_ForSaleYN:                   boolean | null;
  MIAMIRE_Style:                       null | string;
  NumberOfUnitsTotal:                  number | null;
  BuyerOfficeName:                     null | string;
  AssociationFee:                      number | null;
  LeaseAmount:                         null;
  LotSizeSquareFeet:                   number;
  CoBuyerAgentFullName:                null | string;
  TenantPays:                          string[];
  ListingInputOriginalMedia:           null;
  BuyerOfficeKey:                      null | string;
  Electric:                            Electric[];
  ArchitecturalStyle:                  string[];
  NewTaxesExpense:                     null;
  RoomMasterBathroomFeatures:          string[];
  MIAMIRE_MembershipPurchRqdYN:        boolean | null;
  UnparsedAddress:                     string;
  PrivateRemarks:                      null | string;
  InternetConsumerCommentYN:           boolean;
  CoListOfficePhone:                   null | string;
  MIAMIRE_ForLeaseMLSNumber:           null;
  BuildingAreaTotal:                   number | null;
  TransactionBrokerCompensationType:   CompensationType | null;
  OtherEquipment:                      OtherEquipment[];
  HabitableResidenceYN:                boolean;
}

export enum Appliance {
  Dishwasher = "Dishwasher",
  Disposal = "Disposal",
  Dryer = "Dryer",
  ElectricRange = "Electric Range",
  ElectricWaterHeater = "Electric Water Heater",
  FreeStandingFreezer = "Free-Standing Freezer",
  GasRange = "Gas Range",
  GasWaterHeater = "Gas Water Heater",
  IceMaker = "Ice Maker",
  Microwave = "Microwave",
  OtherEquipmentAppliances = "Other Equipment/Appliances",
  Refrigerator = "Refrigerator",
  SelfCleaningOven = "Self Cleaning Oven",
  TrashCompactor = "Trash Compactor",
  WallOven = "Wall Oven",
  Washer = "Washer",
  WaterPurifier = "Water Purifier",
}

export enum Frequency {
  Annually = "Annually",
  Monthly = "Monthly",
  Quarterly = "Quarterly",
}

export enum Units {
  SquareFeet = "Square Feet",
}

export enum CompensationType {
  CompensationType = "$",
  Empty = "%",
}

export enum ConstructionMaterial {
  Brick = "Brick",
  CBSConstruction = "CBS Construction",
  ConcreteBlockConstruction = "Concrete Block Construction",
  ConcreteBlockWithBrick = "Concrete Block With Brick",
  Frame = "Frame",
  Other = "Other",
  PreCastConcreteConstruction = "Pre-Cast Concrete Construction",
  Stucco = "Stucco",
}

export enum Contingency {
  BackupContractCallLA = "Backup Contract/Call LA",
  CloseOfOtherProperty = "Close of Other Property",
  NoContingencies = "No Contingencies",
  PendingInspections = "Pending Inspections",
  SaleOfOtherProperty = "Sale Of Other Property",
  The3RDPartyApproval = "3rd Party Approval",
}

export enum Cooling {
  CeilingFanS = "Ceiling Fan(s)",
  CentralAir = "Central Air",
  CentralBuildingAC = "Central Building A/C",
  CentralIndividualAC = "Central Individual A/C",
  Electric = "Electric",
  Other = "Other",
  PaddleFans = "Paddle Fans",
  WallWindowUnitS = "Wall/Window Unit(s)",
}

export enum CountyOrParish {
  BrowardCounty = "Broward County",
  HendryCounty = "Hendry County",
  HighlandsCounty = "Highlands County",
  MiamiDadeCounty = "Miami-Dade County",
  OtherFloridaCounty = "Other Florida County",
  PalmBeachCounty = "Palm Beach County",
  StLucieCounty = "St Lucie County",
}

export enum CurrentFinancing {
  Cash = "Cash",
  Conventional = "Conventional",
  Fha = "FHA",
  LeasedRenewables = "Leased Renewables",
  Other = "Other",
  PurchaseMoneyMortgage = "Purchase Money Mortgage",
  SellerFinancing = "Seller Financing",
  Va = "VA",
}

export enum DirectionFaces {
  East = "East",
  North = "North",
  Northeast = "Northeast",
  Northwest = "Northwest",
  South = "South",
  Southeast = "Southeast",
  Southwest = "Southwest",
  West = "West",
}

export enum DoorFeature {
  FrenchDoors = "French Doors",
  HighImpactDoors = "High Impact Doors",
}

export enum Electric {
  CircuitBreakers = "Circuit Breakers",
  FuseBox = "Fuse Box",
  The101200Amps = "101-200 Amps",
}

export enum EntryLocation {
  Foyer = "Foyer",
}

export enum Fencing {
  Fence = "Fence",
}

export enum Flooring {
  Carpet = "Carpet",
  CeramicFloor = "Ceramic Floor",
  Concrete = "Concrete",
  Marble = "Marble",
  Other = "Other",
  Parquet = "Parquet",
  Slate = "Slate",
  Terrazzo = "Terrazzo",
  Tile = "Tile",
  Vinyl = "Vinyl",
  Wood = "Wood",
}

export enum FrontageType {
  Bay = "Bay",
}

export enum Furnished {
  Furnished = "Furnished",
  FurnitureForSale = "Furniture For Sale",
  Partially = "Partially",
  PartiallyFurnished = "Partially Furnished",
  Unfurnished = "Unfurnished",
}

export enum Heating {
  Central = "Central",
  CentralBuildingAC = "Central Building A/C",
  CentralElectric = "Central Electric",
  CentralIndividualAC = "Central Individual A/C",
  Electric = "Electric",
  Gas = "Gas",
  HeatPumpReverseCycle = "Heat Pump/Reverse Cycle",
  None = "None",
  Other = "Other",
  WallFurnace = "Wall Furnace",
}

export enum LaundryFeature {
  CommonArea = "Common Area",
  InGarage = "In Garage",
  LaundryRoom = "Laundry Room",
  LaundryTub = "Laundry Tub",
  UtilityRoomLaundry = "Utility Room/Laundry",
  WasherDryerHookUp = "Washer/Dryer Hook-Up",
}

export enum LeaseTerm {
  MoreThan1Year = "More Than 1 Year",
  ShortTermLease = "Short Term Lease",
  The12Months = "12 Months",
  The1To3YearLease = "1 To 3 Year Lease",
  The1YearWithRenewalOption = "1 Year With Renewal Option",
  The710YearLease = "7-10 Year Lease",
}

export enum ListAOR {
  AMiamiAssociationOfREALTORS = "A-Miami Association of REALTORS",
}

export enum ListingAgreement {
  ExclusiveAgency = "Exclusive Agency",
  ExclusiveRightToSell = "Exclusive Right To Sell",
  ExclusiveRightWithException = "Exclusive Right With Exception",
}

export enum ListingTerm {
  AllCash = "All Cash",
  Cash = "Cash",
  Conventional = "Conventional",
  FHAVaApproved = "FHA-Va Approved",
  Fha = "FHA",
  Fha203K = "FHA 203K",
  LeaseOption = "Lease Option",
  NoTerms = "No Terms",
  OtherTerms = "Other Terms",
  OwnerWillCarry = "Owner Will Carry",
  VALoan = "VA Loan",
}

export enum MIAMIRETypeofAssociation {
  Condo = "Condo",
  Homeowners = "Homeowners",
  None = "None",
  Other = "Other",
}

export enum MIAMIRETypeofGoverningBodies {
  Condominium = "Condominium",
  HomeownerAssociation = "Homeowner Association",
  NoGoverningBody = "No Governing Body",
}

export enum MajorChangeType {
  Active = "Active",
  BackOnMarket = "Back On Market",
  Closed = "Closed",
  New = "New",
  Pending = "Pending",
  Rented = "Rented",
}

export interface Media {
  Order:             number | string;
  MediaKey?:         string;
  MediaURL:          string;
  ResourceRecordKey: string;
  ResourceName:      ResourceName;
  ClassName:         PropertyType;
  MediaCategory:     MediaMediaCategory;
  MimeType:          MIMEType;
  MediaObjectID:     string;
  ShortDescription:  null | string;
}

export enum PropertyType {
  CommercialSale = "Commercial Sale",
  LandBoatDocks = "Land/Boat Docks",
  Residential = "Residential",
  ResidentialIncome = "Residential Income",
  ResidentialLease = "Residential Lease",
}

export enum MediaMediaCategory {
  Photo = "Photo",
}

export enum MIMEType {
  ApplicationPDF = "application/pdf",
  ImageJPEG = "image/jpeg",
}

export enum ResourceName {
  Property = "Property",
}

export enum OriginatingSystem {
  Miamire = "miamire",
}

export enum OriginatingSystemName {
  MiamiAssociationOfREALTORS = "Miami Association of REALTORS®",
}

export enum OtherEquipment {
  AutomaticGarageDoorOpener = "Automatic Garage Door Opener",
  Elevator = "Elevator",
  Intercom = "Intercom",
  NaturalGas = "Natural Gas",
  NoEquipment = "No Equipment",
  SatelliteDish = "Satellite Dish",
  TVAntenna = "TV Antenna",
}

export enum OtherStructure {
  ExtraBuildingShed = "Extra Building/Shed",
  None = "None",
  ShedS = "Shed(s)",
}

export enum PatioAndPorchFeature {
  AwningS = "Awning(s)",
  Deck = "Deck",
  OpenPorch = "Open Porch",
  Patio = "Patio",
  PorchBalcony = "Porch/Balcony",
  Screened = "Screened",
  ScreenedPorch = "Screened Porch",
  WrapAround = "Wrap Around",
}

export enum PetsAllowed {
  CatsOK = "Cats OK",
  DogsOK = "Dogs OK",
  Maximum20Lbs = "Maximum 20 Lbs",
  MoreThan20Lbs = "More Than 20 Lbs",
  No = "No",
  RestrictionsOrPossibleRestrictions = "Restrictions Or Possible Restrictions",
  Yes = "Yes",
}

export enum Possession {
  BeforeClosing = "Before Closing",
  Funding = "Funding",
  Negotiable = "Negotiable",
  Other = "Other",
  RentalAgreement = "Rental Agreement",
}

export enum PossibleUse {
  Investment = "Investment",
  Primary = "Primary",
  Secondary = "Secondary",
  UnknownWithheld = "Unknown/Withheld",
}

export enum PropertyCondition {
  CompletelyRenovated = "Completely Renovated",
  NewConstruction = "New Construction",
  SubstantiallyRemodeled = "Substantially Remodeled",
  UpdatedRemodeled = "Updated/Remodeled",
}

export enum PropertySubType {
  Apartment = "Apartment",
  Commercial = "Commercial",
  Condominium = "Condominium",
  Dockominium = "Dockominium",
  Duplex = "Duplex",
  MultiFamily = "Multi Family",
  Quadruplex = "Quadruplex",
  Residential = "Residential",
  SingleFamilyResidence = "Single Family Residence",
  Townhouse = "Townhouse",
  Triplex = "Triplex",
}

export enum RoomBedroomFeature {
  AtLeast1BedroomGroundLevel = "At Least 1 Bedroom Ground Level",
  EntryLevel = "Entry Level",
  MasterBathShower = "Master Bath Shower",
  MasterBathTub = "Master Bath Tub",
  MasterBedroomGroundLevel = "Master Bedroom Ground Level",
  MasterBedroomUpstairs = "Master Bedroom Upstairs",
  None = "None",
  Other = "Other",
  SittingAreaMasterBedroom = "Sitting Area - Master Bedroom",
  Studio = "Studio",
}

export enum RoomDiningRoomFeature {
  BreakfastArea = "Breakfast Area",
  DiningLivingRoom = "Dining/Living Room",
  EatInKitchen = "Eat-In Kitchen",
  FamilyDiningCombination = "Family/Dining Combination",
  FloridaDiningCombination = "Florida/Dining Combination",
  FormalDining = "Formal Dining",
  KitchenDining = "Kitchen Dining",
  Other = "Other",
  SnackBarCounter = "Snack Bar/Counter",
}

export enum Sewer {
  AtSite = "At Site",
  Other = "Other",
  PublicSanitation = "Public Sanitation",
  PublicSewer = "Public Sewer",
  SepticTank = "Septic Tank",
  Sewer = "Sewer",
}

export enum ShowingContactType {
  Agent = "Agent",
  CallListingOffice = "Call Listing Office",
  Occupant = "Occupant",
  Owner = "Owner",
}

export enum SpecialListingCondition {
  Lease = "Lease",
  RealEstateOwned = "Real Estate Owned",
  ShortSale = "Short Sale",
}

export enum StateOrProvince {
  FL = "FL",
}

export enum StreetDirPrefix {
  E = "E",
  N = "N",
  Ne = "NE",
  Nw = "NW",
  S = "S",
  SE = "SE",
  Sw = "SW",
  W = "W",
}

export interface Supplement {
  Order:             string;
  MediaKey:          string;
  MediaURL:          string;
  ResourceRecordKey: string;
  ResourceName:      ResourceName;
  ClassName:         PropertyType;
  MediaCategory:     SupplementMediaCategory;
  MimeType:          MIMEType;
  MediaObjectID:     string;
  ShortDescription:  string;
}

export enum SupplementMediaCategory {
  PDF = "PDF",
}

export enum WaterSource {
  MunicipalWater = "Municipal Water",
  Other = "Other",
  Public = "Public",
  Well = "Well",
}

export enum YearBuiltDetails {
  CondoConversion = "Condo-Conversion",
  EffectiveYearBuilt = "Effective Year Built",
  NewConstruction = "New Construction",
  Resale = "Resale",
  Unknown = "Unknown",
}
